workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.mood-ai.moviesapp
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.mood-ai.moviesapp"
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...) # Add your App Store Connect Issuer ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...) # Add your App Store Connect Key ID
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # Add your App Store Connect Private Key
        FIREBASE_TOKEN: Encrypted(...) # Add your Firebase CI token
        FIREBASE_APP_ID_IOS: Encrypted(...) # Add your Firebase iOS App ID
      flutter: stable
      cocoapods: default
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # Firebase App Distribution (Optional - remove if not using)
      # firebase:
      #   firebase_token: $FIREBASE_TOKEN
      #   ios:
      #     app_id: $FIREBASE_APP_ID_IOS
      #     groups:
      #       - testers
      # Email notifications
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true

  android-workflow:
    name: Android Workflow
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
      vars:
        FIREBASE_TOKEN: Encrypted(...) # Add your Firebase CI token
        FIREBASE_APP_ID_ANDROID: Encrypted(...) # Add your Firebase Android App ID
      flutter: stable
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build APK with Flutter
        script: |
          flutter build apk --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      # Firebase App Distribution (Optional - remove if not using)
      # firebase:
      #   firebase_token: $FIREBASE_TOKEN
      #   android:
      #     app_id: $FIREBASE_APP_ID_ANDROID
      #     groups:
      #       - testers
      # Email notifications
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true 