workflows:
  flutter-ios-simulator:
    name: Flutter iOS Simulator
    environment:
      flutter: stable
      cocoapods: default
      xcode: 16.2
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.mood-ai.moviesapp"
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - flutter build ios --simulator --flavor staging  # --flavor is optional
    artifacts:
      - build/ios/iphonesimulator/Runner.app
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      # ios_signing: # Disabled for Firebase Test Lab - no code signing needed
      #   distribution_type: development
      #   bundle_identifier: com.mood-ai.moviesapp
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.mood-ai.moviesapp"
        # Environment variables below are optional - only needed for automatic distribution
        # APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        # APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER  
        # APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        # FIREBASE_TOKEN: $FIREBASE_TOKEN
        # FIREBASE_APP_ID_IOS: $FIREBASE_APP_ID_IOS
      flutter: stable
      cocoapods: default
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      # - name: Flutter analyze  # Disabled due to issues in forked speech_to_text package
      #   script: |
      #     flutter analyze
      # - name: Flutter unit tests  # Disabled - no test directory exists
      #   script: |
      #     flutter test
      #   ignore_failure: true
      - name: Flutter build iOS app for Test Lab (no code signing)
        script: |
          flutter build ios --release --no-codesign \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
      - name: Create IPA for Test Lab
        script: |
          echo "Creating IPA for Firebase Test Lab..."
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../ipa/Runner.ipa Payload/
          cd ../../..
          echo "IPA created at build/ios/ipa/Runner.ipa"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/Runner.xcarchive
      - build/ios/Runner.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # Firebase App Distribution (Optional - remove if not using)
      # firebase:
      #   firebase_token: $FIREBASE_TOKEN
      #   ios:
      #     app_id: $FIREBASE_APP_ID_IOS
      #     groups:
      #       - testers
      # Email notifications
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true

  android-workflow:
    name: Android Workflow
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      # android_signing:
      #   - keystore_reference
      # vars:
      #   # Environment variables below are optional - only needed for automatic distribution
      #   # FIREBASE_TOKEN: $FIREBASE_TOKEN
      #   # FIREBASE_APP_ID_ANDROID: $FIREBASE_APP_ID_ANDROID
      flutter: stable
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      # - name: Flutter analyze  # Disabled due to issues in forked speech_to_text package
      #   script: |
      #     flutter analyze
      # - name: Flutter unit tests  # Disabled - no test directory exists
      #   script: |
      #     flutter test
      #   ignore_failure: true
      - name: Build APK with Flutter
        script: |
          flutter build apk --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      # Firebase App Distribution (Optional - remove if not using)
      # firebase:
      #   firebase_token: $FIREBASE_TOKEN
      #   android:
      #     app_id: $FIREBASE_APP_ID_ANDROID
      #     groups:
      #       - testers
      # Email notifications
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true 