name: mood_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  go_router: ^16.0.0
  nested: ^1.0.0
  shared_preferences: ^2.2.3
  crypto: ^3.0.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  rxdart: ^0.28.0
  speech_to_text: ^7.1.0
  audio_flux: ^1.2.1
  flutter_soloud: ^3.2.1
  flutter_recorder: ^1.1.2
  flutter_dotenv: ^5.1.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
