name: mood_ai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^12.1.1
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  path: ^1.8.3
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  share_plus: ^7.2.1
  speech_to_text:
    path: packages/speech_to_text-6.5.1/speech_to_text
  avatar_glow: ^3.0.0
  permission_handler: ^11.3.1
  http: ^1.2.1
  csv: ^6.0.0
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  rxdart: ^0.28.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  firebase_app_distribution: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/big_movies.db
    - assets/ewv9cs.xz
    - assets/lrmid1.torrent
