// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXol_P5EcQ3xDW5vCssdNgnEpYb8hYTxA',
    appId: '1:515870596935:web:f76bc3dc7e3d6180b77662',
    messagingSenderId: '515870596935',
    projectId: 'mood-ai-e442e',
    authDomain: 'mood-ai-e442e.firebaseapp.com',
    storageBucket: 'mood-ai-e442e.firebasestorage.app',
    measurementId: 'G-E1N9W8HM30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ7T9ZxJxWYmy4F3pS_A6qf_vqa528GiI',
    appId: '1:515870596935:android:c6999bf3fc64c449b77662',
    messagingSenderId: '515870596935',
    projectId: 'mood-ai-e442e',
    storageBucket: 'mood-ai-e442e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsZNchhB-3RvKpvSRD2-jdqHWTlyXXEeE',
    appId: '1:515870596935:ios:90de11fd0eba454ab77662',
    messagingSenderId: '515870596935',
    projectId: 'mood-ai-e442e',
    storageBucket: 'mood-ai-e442e.firebasestorage.app',
    iosBundleId: 'com.example.moodAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsZNchhB-3RvKpvSRD2-jdqHWTlyXXEeE',
    appId: '1:515870596935:ios:90de11fd0eba454ab77662',
    messagingSenderId: '515870596935',
    projectId: 'mood-ai-e442e',
    storageBucket: 'mood-ai-e442e.firebasestorage.app',
    iosBundleId: 'com.example.moodAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXol_P5EcQ3xDW5vCssdNgnEpYb8hYTxA',
    appId: '1:515870596935:web:03123c67fe09537cb77662',
    messagingSenderId: '515870596935',
    projectId: 'mood-ai-e442e',
    authDomain: 'mood-ai-e442e.firebaseapp.com',
    storageBucket: 'mood-ai-e442e.firebasestorage.app',
    measurementId: 'G-6JHRNRCRDK',
  );
}
